# nixpacks.toml

# --- 빌드 단계를 정의합니다 ---
[phases.build]
# 1. Gradle 빌드를 실행하고,
# 2. (디버깅용) 빌드 결과물이 잘 생성되었는지 로그에 출력합니다.
cmds = ["./gradlew clean build", "echo '--- JAR file location ---'", "ls -R /app/build/libs"]

# --- 실행 단계를 정의합니다 ---
[start]
# 1. build/libs 폴더에서 .jar 파일을 찾아 서버를 실행합니다.
cmd = "java -jar -Dserver.port=$PORT /app/build/libs/*.jar"