spring:
  profiles:
    active: dev
  application:
    name: discodeitß
file:
  upload:
    # OS별 외부 파일 저장 경로 설정
    windows:
      # 윈도우 OS용 파일 업로드 기본 경로
      path: C:/myWs/uploadedFiles
    mac:
      # macOS용 파일 업로드 기본 경로
      # /Users/mac/ 이부분이 각자 컴퓨터 맞게
      path: /Users/mac/myWs/uploadedFilesimg
cookie:
  key: 2_]08iD^zr6]9AbverLgyhbBYu(VcIBN

discodeit:
  jwt:
    access-token:
      secret: test-access-token-secret-key-for-jwt-token-generation-and-validation-must-be-long-enough-for-testing
      expiration-ms: 1800000 # 30 minutes
    refresh-token:
      secret: test-refresh-token-secret-key-for-jwt-token-generation-and-validation-must-be-different-and-long-for-testing
      expiration-ms: 604800000 # 7 days
