package com.sprint.mission.discodeit.exception;

public enum ErrorCode {

    USER_NOT_FOUND,
    DUPLICATE_USER,

    CHANNEL_NOT_FOUND,
    PRIVATE_CHANNEL_UPDATE,
    CHANNEL_ALREADY_EXISTS,

    MESSAGE_NOT_FOUND,

    USER_STATUS_NOT_FOUND,
    DUPLICATE_USER_STATUS,

    READ_STATUS_NOT_FOUND,
    DUPLICATE_READ_STATUS,

    BINARY_CONTENT_NOT_FOUND;
}
